packages:
  - 'packages/*'
  - 'packages/dataValidation'
  - 'packages/responseVisualizer'
  - 'packages/webapp'
  - 'packages/ennube-salesforce'
  - 'packages/contractReader'

catalog:
  react: ^18.3.1
  zod: ^3.25.76