packages:
  - 'packages/*'
  - 'packages/dataValidation'
  - 'packages/responseVisualizer'
  - 'packages/webapp'
  - 'packages/ennube-salesforce'
  - 'packages/contractReader'
  - 'packages/embedder-api'

catalog:
  zod: ^3.25.76