export const agents = [
    {
      id: 1,
      name: "Data Steward",
      apiName: 'data-steward',
      role: "Data Management Expert",
      description:
        "Maintains the quality of data in your CRM by leveraging online search tools to verify, enrich, and clean customer information.",
      image: "/data-steward.png",
      link: "/agents/data-steward",
      categories: ["data", "management", "quality"],
      skills: ["data cleaning", "verification", "enrichment", "standardization"],
      isNew: false,
      comingSoon: false,
      hasImage: true,
    },
    {
      id: 2,
      name: "Prospect Finder",
      apiName: 'prospect-finder',
      role: "Lead Generation Specialist",
      description: "Helps with creating your ideal customer profiles and finds matching prospects while incorporating feedback from users.",
      image: "/prospect-finder.png",
      link: "/agents/prospect-finder",
      categories: ["sales", "leads", "prospecting"],
      skills: ["lead generation", "customer profiling", "prospect research", "qualification"],
      isNew: true,
      comingSoon: false,
      hasImage: true,
    },
    {
      id: 5,
      name: "Contract Reader",
      apiName: 'contract-reader',
      role: "Contract Intelligence Assistant",
      description:
        "Keeps your contracts and CRM in sync by reviewing legal agreements, extract key terms, and automatically updating your CRM fields—so your data stays accurate, auditable, and compliant.",
      image: "/contracts-reader.png",
      link: "/agents/contracts-reader",
      categories: ["contracts", "compliance", "crm", "legal"],
      skills: ["contract extraction", "crm sync", "compliance monitoring", "agreement cross-referencing"],
      isNew: true,
      comingSoon: false,
      hasImage: true,
    },
    {
      id: 3,
      name: "Meetings Booker",
      apiName: 'meetings-booker',
      role: "Scheduling Specialist",
      description:
        "Sets up appointments with prospects identified by the Prospect Finder, handling scheduling, reminders, and follow-ups.",
      image: "/meetings-booker.png",
      link: "/agents/meetings-booker",
      button: null,
      categories: ["sales", "scheduling", "productivity"],
      skills: ["meeting scheduling", "calendar management", "follow-up", "reminders"],
      isNew: false,
      comingSoon: true,
      hasImage: true,
    },
    {
      id: 4,
      name: "Market Nurturer",
      apiName: 'market-nurturer',
      role: "Relationship Builder",
      description:
        "Nurtures long-term buying prospects through personalized content, timely communications, and relationship building.",
      image: "/market-nurturer.png",
      link: "/agents/market-nurturer",
      button: null,
      categories: ["marketing", "nurturing", "communication"],
      skills: ["content personalization", "email campaigns", "lead nurturing", "relationship management"],
      isNew: false,
      comingSoon: true,
      hasImage: true,
    }
    
];
